// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars,avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCh6vvtt6jnaU3ddSnbTKZuAUVs2TLA7Y',
    appId: '1:555352782831:web:ea5f56adc972a8071c681a',
    messagingSenderId: '555352782831',
    projectId: 'fir-homework-5024c',
    authDomain: 'fir-homework-5024c.firebaseapp.com',
    storageBucket: 'fir-homework-5024c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaKQNWevCEp2nsypNF7iZsaV5Uc3wkm0c',
    appId: '1:555352782831:android:cbc6d8a4b231ea541c681a',
    messagingSenderId: '555352782831',
    projectId: 'fir-homework-5024c',
    storageBucket: 'fir-homework-5024c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIynMD0Cysb6lkH64mLdrGs5zK--htNQ',
    appId: '1:555352782831:ios:08be7a8c2fff47041c681a',
    messagingSenderId: '555352782831',
    projectId: 'fir-homework-5024c',
    storageBucket: 'fir-homework-5024c.appspot.com',
    iosClientId: '555352782831-n8ln2t6h7mgadduigms3n97c3ufduq7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioVer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIynMD0Cysb6lkH64mLdrGs5zK--htNQ',
    appId: '1:555352782831:ios:08be7a8c2fff47041c681a',
    messagingSenderId: '555352782831',
    projectId: 'fir-homework-5024c',
    storageBucket: 'fir-homework-5024c.appspot.com',
    iosClientId: '555352782831-n8ln2t6h7mgadduigms3n97c3ufduq7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioVer1',
  );
}
